config/routes.rb
Rails.application.routes.draw do
  # get 'user/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :activities
  resources :users
  resource :session
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = @current_user
    @activity.save!
    redirect_to index
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to @activity
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to @activity
  end


  private

  def activity_params
    params.require(:activity).permit(:title, :user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
        if @user.password === params[:user][:password]
          flash[:notice] = "You're signed in!"
          session[:user_id] = @user.id
          redirect_to root_path
        else
          flash[:alert] = "Wrong password!"
          redirect_to new_session_path
        end
      else
        flash[:alert] = "That user doesn't exists!"
      end
  end

  def destroy
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]



  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  else
    flash.now[:alert] = "Fields are incomplete"
    render :new
  end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def logged_in_user
    unless logged_in?
      flash[:alert] = "Please log in."
      render :new
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user === current_user?(@user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @activities = Activity.all
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/essions_helper.rb
module EssionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/edit.html.erb
<%= form_for @activity do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

<%= f.submit %>
<% end %>

<p><%= link_to '(delete)', activity_path(@activity),
    method: :delete,
    data: {confirm: "Are you sure?"} %>
</p>

app/views/activities/index.html.erb
<br>
<div class="activities">

<h2>Check out this list of things to do</h2>

<br>
<%= form_for [@user, @activity] do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>


<%= f.submit :submit %>
<% end %>


<br>
<% @activities.each do |activity| %>
  <% if @current_user %>
    <div class="activelist">
      <%=  activity.title %>
      <% if activity.user.id == @current_user.id %>
      <p id="edit">
        <%= link_to '(edit)', edit_activity_path(activity) %>
      </p>
      <% end %>
    </div>
  <% else %>
  <div class="activelist">
    <%=  activity.title %>
  </div>
  <% end %>
<% end %>
</div>

app/views/activities/new.html.erb
<%= form_for [@user, @activity] do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>


<%= f.submit %>
<% end %>

app/views/activities/show.html.erb
<h2><%= @activity.title %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makali</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="http://www.drodd.com/images14/m41.jpg" sizes="32x32">
    <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
  </head>

  <body>
    <nav>
      <ul>
        <li>
          <h1 id="header"><%= link_to "Makali", root_path %></h1>
        </li>
        <% if @current_user %>
            <%= link_to "#{@current_user.username}", user_path(@current_user) %>
            <li class="sign">
              <%= link_to 'SIGN OUT', session_path, method: :delete %>
            </li>
        <% else %>
            <li class="sign">
              <%= link_to 'SIGN UP', new_user_path %>
            </li>
        <li class="sign">
          <%= link_to 'SIGN IN', new_session_path %>
        </li>
        <% end %>
      </ul>
    </nav>
    <br>
    <% flash.each do |type, message| %>
      <p class='<%= type %>'><%= message %></p>
    <% end %>
    <br>


    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div id="newuserform">
<%= form_for @user do |f| %>
  <div class='userform'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class='userform'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

<%= f.submit "Submit" %>
<% end %>
</div>

app/views/welcome/index.html.erb
<h2 class="welcome">There's always something to do.</h2>


<ul class="generate">
  <li>
    <h2 id="live">
      You should ...
    </h2>

  </li>
  <li>
    <div id="content">
      <% @activities.shuffle.first(1).each do |activity| %>
      <%= activity.title %>
      <% end %>
    </div>
  </li>

  <!-- <div id="makali">
  </div> -->
</ul>



<h2 class="welcome" id="all">
  <%= link_to 'View All Activities', activities_path  %>
</h2>